core/urls.py
from django.contrib import admin
from django.urls import include, path
from . views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('forecast/', include(('forecast.urls', 'forecast'), namespace='forecast')),

]

forecast/urls.py
from django.urls import path
from .views import (
    ForeForm,
    ForecastLoadDatabaseView
)

urlpatterns = [
    path('', ForeForm.as_view(), name='analysis_result'),
    path('analysis_load_db', ForecastLoadDatabaseView.as_view(),
         name='analysis_load_db'),
]

forecast/models.py
from django.db import models

# Create your models here.

forecast/forms.py
from django import forms


class ForecastForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super(ForecastForm, self).__init__(*args, **kwargs)
        self.fields['forecastedate'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'YYYY/M/D'})
        self.fields['area_id'].widget.attrs.update(
            {'class': 'form-control'})
        self.fields['scenarioname'].widget.attrs.update(
            {'class': 'form-control'})

    SCENARIONAME = (
        ('EC-P25', 'EC-P25'),
        ('EC-P50', 'EC-P50'),
        ('EC-P75', 'EC-P75')
    )
    AREAID = (
        (1, 'AreaID 1'),
        (2, 'AreaID 2'),
        (3, 'AreaID 3'),
        (4, 'AreaID 4')
    )

    forecastedate = forms.CharField(label='Forecast Date')
    scenarioname = forms.ChoiceField(
        choices=SCENARIONAME, label='Scenario Name')
    area_id = forms.ChoiceField(choices=AREAID, label='AreaID')

core/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "home.html"

forecast/views.py
import os
import json
import mysql.connector
from mysql.connector import Error
from django.views.generic import TemplateView, FormView
from . forms import ForecastForm

# Django CBV Class Based Views


class ForeForm(FormView):
    template_name = 'forecast/analysis_result.html'
    form_class = ForecastForm
    success_url = '/forecast'

    def form_valid(self, form, **kwargs):
        context = self.get_context_data(**kwargs)

        # Load data for analysis
        _path = os.path.dirname(__file__)
        with open(_path+'/data_for_analysis_db.json', 'r') as f:
            data = json.load(f)

        # Get the form data
        ForecastDate = form.cleaned_data['forecastedate']
        ScenarioName = form.cleaned_data['scenarioname']
        AreaID = int(form.cleaned_data['area_id'])

        # Prepare data for plotting
        result_plot = [
            item for item in data if
            item['ForecastDate'].split(' ')[:-1] == [ForecastDate]
            and item['ScenarioName'] == ScenarioName
            and item['AreaID'] == AreaID
        ]
        context['plot'] = result_plot
        context['form'] = ForecastForm
        return self.render_to_response(context)


class ForecastLoadDatabaseView(TemplateView):
    template_name = 'forecast/analysis_result.html'

    def get_context_data(self, **kwargs):

        try:
            connection = mysql.connector.connect(
                host='testeflow.c3u0viwxwdgw.us-east-1.rds.amazonaws.com',
                database='teste_admin',
                user='teste_user',
                password='teste_devFullStack',
                port='3306',
            )
            if connection.is_connected():
                cursor = connection.cursor(dictionary=True)

            sql_select_Query = "SELECT * FROM example_table\
                WHERE VarID=1\
                AND AreaType='System'\
                AND ForecastDate BETWEEN '2020-02-15' AND '2020-03-25'\
                AND AreaID BETWEEN '1' AND '4'\
                AND ScenarioName IN ('EC-P25', 'EC-P50', 'EC-P75')"

            cursor.execute(sql_select_Query)
            result_filter = cursor.fetchall()

            # Selecting the data of interest
            data_for_analysis = [
                item for item in result_filter if item['TargetLabel'] == '2020-W14']

            # Saves the data in json format for analysis
            _path = os.path.dirname(__file__)
            with open(_path+'/data_for_analysis_db.json', 'w', encoding='utf-8') as f:
                json.dump(data_for_analysis, f,
                          ensure_ascii=False, default=str)

        except Error as e:
            print("Error while connecting to MySQL", e)
        finally:
            if (connection.is_connected()):
                cursor.close()
                connection.close()
        return {'data': 'data'}

forecast/templates/forecast/analysis_result.html
{% extends "base.html" %}
{% load static %}
{% block title %} Flow Energia - Analysis {% endblock %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    <div class="form-row">
        {% for field in form %}
        <div class="form-group col-md-4">
            {{ field.label }}
            {{ field }}
        </div>
        {% endfor %}
    </div>
    <button type="submit" class="btn btn-primary">Filter</button>
</form>
<canvas id="line-chart" width="600" height="250"></canvas>
<div>
    <h3>Forecast based on first week</h3>
    <table class="table table-striped">
        <thead>
            <tr>
                {% for resul  in plot %}
                <th scope="col">{{ resul.ScenarioType }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            <tr>
                {% for resul  in plot %}
                <td>{{ resul.Value }}</td>
                {% endfor %}
            </tr>
        </tbody>
    </table>
</div>
{% endblock %}

{% block plus_js %}
<script src="{% static 'bootstrap/js/jquery-2.1.1.min.js' %}"></script>
<script src="{% static 'bootstrap/js/jquery-mask-1.14.10.js' %}"></script>
<script src="{% static 'bootstrap/js/mask.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>

<script>
    /*
        Os Arrays labels e data não consegui converter os valores de forma que carregasse
        o grafico, deixei um resultado fixo apenas para visualizar como ficaria.
    */
    new Chart(document.getElementById("line-chart"), {
        type: 'line',
        data: {
            labels: ['2020/04-rv0', '2020/04-rv1', '2020/04-rv2', '2020/04-rv3'],
            datasets: [{
                data: [55515.00000, 55440.00000, 55440.00000, 55440.00000],
                label: "Abril",
                borderColor: "#3e95cd",
                fill: true
            },
            ]
        },
        options: {
            title: {
                display: true,
                text: 'Forecast based on first week'
            }
        }
    });


</script>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="{% block description %}{% endblock description %}" />
    <meta name="keywords" content="{% block keywords %}{% endblock %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/base.css' %}">
    {% block plus_css %}{% endblock %}
</head>

<body>
    {% block menu %}
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <h5 class="my-0 mr-md-auto font-weight-normal">
            Flow Energia</h5>
        <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
            <a class="p-2 text-dark" href="{% url 'forecast:analysis_result' %}">Analyze with local DB</a>
            <a class="p-2 text-dark" href="{% url 'forecast:analysis_load_db' %}">Load DataBase</a>

        </nav>
    </div>
    {% endblock %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    {% block footer %}
    <div class="container">
        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                <div class="col-12 col-md text-center">
                    <small class="d-block mb-3 text-muted">Flow Energia 2020</small>
                </div>
            </div>
        </footer>
    </div>
    {% endblock %}
</body>

{% block plus_js %}{% endblock %}

</html>

templates/home.html
{% extends "base.html" %}
{% block title %}Flow Energia - Home {% endblock %}
{% block content %}
<row>
    <div class="col-sm-12">
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Welcome!</h1>
            <h3 class="lead">
                Flow Energia makes analyzes for the sale and purchase of electricity.
            </h3>
            <p>Access the menu to view the latest results.</p>
        </div>
    </div>
</row>
{% endblock %}